// AUTO-GENERATED by scripts/gen-sitemap-lastmod.mjs — do not edit by hand.
//
// Regenerate with: npm run sitemap:lastmod
// Prove it is in sync: npm run sitemap:lastmod:check
//
// Each static route's date is `git log -1 --format=%cs` for the source files
// that render that route, so a sitemap URL reports the date of its OWN last
// significant source change and not a shared build/run timestamp.
/* eslint-disable */

/** static route -> the source paths that render it. */
export const ROUTE_SOURCES: Record<string, string[]> = {
  "/": [
    "src/app/page.tsx",
    "src/components/landing",
  ],
  "/blog": [
    "src/app/blog/page.tsx",
    "src/components/blog",
    "src/lib/blog",
  ],
  "/docs": [
    "src/app/docs/page.tsx",
  ],
  "/social-media-bot": [
    "src/app/social-media-bot/page.tsx",
  ],
};

/** static route -> newest commit date (%cs) among that route's source paths. */
export const ROUTE_LASTMOD: Record<string, string> = {
  "/": "2026-09-15",
  "/blog": "2026-09-15",
  "/docs": "2026-07-24",
  "/social-media-bot": "2026-09-15",
};

/**
 * Newest generated value. Last-resort fallback so no sitemap entry can ever be
 * emitted without a lastmod; still source-derived, never the request time.
 */
export const LATEST_ROUTE_LASTMOD = "2026-09-15";
