import {
  LATEST_ROUTE_LASTMOD,
  ROUTE_LASTMOD,
} from "./sitemap-lastmod.generated";

/**
 * Sitemap freshness helpers.
 *
 * Google only trusts `<lastmod>` it finds reliable, and its guidance is that the
 * value must be "the date of last significant modification" for THAT URL. A
 * sitemap that omits lastmod on some URLs, or stamps every URL with the same
 * build/run date, is discounted or ignored. So:
 *
 * - a static route's date comes from `git log -1 --format=%cs` for the source
 *   files that render it (regenerated by `npm run sitemap:lastmod`);
 * - a blog post's date is its own publish date;
 * - a category's date is the newest post in that category.
 *
 * Every helper here returns a value for the URL it is called for, never the
 * current time, so no entry can be emitted without a per-URL lastmod.
 */

const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/;

/** The date a static route's own source last changed. */
export function routeLastmod(route: string): string {
  return ROUTE_LASTMOD[route] ?? LATEST_ROUTE_LASTMOD;
}

/** Newest ISO date among the given candidates (source-derived, never "now"). */
export function newestDate(
  candidates: Array<string | null | undefined>
): string {
  const valid = candidates
    .filter((date): date is string => typeof date === "string" && ISO_DATE.test(date))
    .sort();
  return valid.length ? valid[valid.length - 1] : LATEST_ROUTE_LASTMOD;
}

/** A per-URL `<lastmod>` Date for an ISO `YYYY-MM-DD` value. */
export function toLastModified(date: string): Date {
  return new Date(`${date}T00:00:00.000Z`);
}
