import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

describe("article agent skills", () => {
  it("ships the five-agent editorial workflow with separated ownership", () => {
    const orchestrator = readFileSync(join(process.cwd(), "article-agent/skills/editorial-orchestrator.md"), "utf8");
    const researcher = readFileSync(join(process.cwd(), "article-agent/skills/source-research-agent.md"), "utf8");
    const strategist = readFileSync(join(process.cwd(), "article-agent/skills/editorial-strategist-agent.md"), "utf8");
    const writer = readFileSync(join(process.cwd(), "article-agent/skills/article-writer-agent.md"), "utf8");
    const reviewer = readFileSync(join(process.cwd(), "article-agent/skills/adversarial-reviewer-agent.md"), "utf8");

    expect(orchestrator).toContain("Permit at most two targeted article revisions");
    expect(orchestrator).toContain("No agent in this workflow receives publish");
    expect(orchestrator).toContain("at least 20 unique, inspected external sources");
    expect(orchestrator).toContain("research_insufficient");
    expect(researcher).toContain("Do not choose an angle, draft prose");
    expect(researcher).toContain("2 X, 2 Reddit, 2 LinkedIn");
    expect(researcher).toContain("Social/community sources are discovery signals");
    expect(researcher).toContain("research_insufficient");
    expect(strategist).toContain("Do not verify evidence, write final prose");
    expect(writer).toContain("Never mark your own article passed");
    expect(reviewer).toContain("Read-only boundary");
    expect(reviewer).toContain("Do not enforce a raw quota");
  });

  it("ships an anti AI slop skill in the loaded article skills directory", () => {
    const skill = readFileSync(join(process.cwd(), "article-agent/skills/anti-ai-slop.md"), "utf8");
    const system = readFileSync(join(process.cwd(), "article-agent/skills/article-generation-system.md"), "utf8");
    const prompt = readFileSync(join(process.cwd(), "article-agent/prompt.md"), "utf8");
    const exporter = readFileSync(join(process.cwd(), "scripts/export-medium-public-preview.mjs"), "utf8");
    const previewVerifier = readFileSync(join(process.cwd(), "scripts/verify-medium-public-preview.mjs"), "utf8");

    expect(skill).toContain("Anti AI Slop Article Skill");
    expect(skill).toContain("petergyang/no-ai-slop");
    expect(skill).toContain("store its `What changed` report in `evals/`");
    expect(skill).toContain("not X, but Y");
    expect(skill).toContain("Best-Author Negation Rule");
    expect(skill).toContain("did not invent/discover/build X; it captured/inherited/revealed X");
    expect(skill).toContain("Run the Best-Author Negation Rule and record the counts before export.");
    expect(skill).toContain("Whole-Article Syntax And Motif Rule");
    expect(skill).toContain("A passing linter does not clear this manual adversarial gate.");
    expect(skill).toContain("one-sentence dramatic paragraphs");
    expect(skill).toContain("Directness: does it say the thing without announcing itself?");
    expect(skill).toContain("Specificity: are abstractions backed by concrete claims");
    expect(skill).toContain("This is an editorial accountability pass first and a voice cleanup pass second.");
    expect(skill).toContain("What would a skeptical expert object to?");
    expect(skill).toContain("Important factual claims need nearby support.");
    expect(skill).toContain("Match language strength to evidence strength.");
    expect(skill).toContain("The article must contain author judgment, not just clean summary.");
    expect(skill).toContain("Reframing Reality Rule");
    expect(skill).toContain("Reshare Velocity Rule");
    expect(skill).toContain("New-School Narrative Rule");
    expect(skill).toContain("sharper model grounded in evidence, causality, and concrete consequences");
    expect(skill).toContain("two-factor authentication made of tissue");
    expect(skill).toContain("AI may assist the workflow, but the author owns final judgment, sourcing, and wording.");
    expect(skill).toContain("Current Technique Research Gate");
    expect(skill).toContain("Brainlift-Style Evidence Gate");
    expect(skill).toContain("Max Voice Anti-Formula Gate");
    expect(skill).toContain("A useful test:");
    expect(skill).toContain("paired aphorisms");
    expect(skill).toContain("attributed critic spotlights");
    expect(skill).toContain("unbulleted `Label: definition` fragments");
    expect(skill).toContain("Do not manufacture quote-worthy lines.");
    expect(skill).toContain("Do not plan slogans or lines for retelling");
    expect(skill).toContain("Do not force every heading into a miniature story or slogan.");
    expect(skill).not.toContain("one or two lines worth retelling");
    expect(skill).not.toContain("every H2 should teach a mini-story by itself");
    expect(skill).toContain("contradiction board");
    expect(skill).toContain("Research sharpens the article; it is not padding.");
    expect(skill).toContain("If the FAQ repeats the article, replace it with a compact `What to remember` box.");
    expect(skill).toContain("If the block sounds like it could open any AI-generated explainer, rewrite it.");
    expect(skill).toContain("If the draft has a reading map, takeaway box, primary action, and conclusion, cut or merge at least one.");
    expect(skill).toContain("The bio must not undercut the article's trust posture.");
    expect(system).toContain("the editorial spine, source proximity, proportional language, human judgment, and reader trust");
    expect(system).toContain("pre-draft generation constraint");
    expect(system).toContain("evals/no-ai-slop-changes-vN.md");
    expect(system).toContain("source truth, claim support, source ownership");
    expect(system).toContain("Never inherit a passing rating for changed prose.");
    expect(system).toContain("Treat executable lint as necessary but incomplete.");
    expect(system).toContain("Run a reliability reviewer before Max review");
    expect(system).toContain("publicPreviewRetained");
    expect(system).toContain("qualityReviewerVetoCleared");
    expect(system).toContain("require title >= 9.2/10 plus subtitle >= 9.2/10 before preview export");
    expect(prompt).toContain("Apply anti-formula constraints before the first draft");
    expect(prompt).toContain("petergyang/no-ai-slop");
    expect(prompt).toContain("Do not prompt for standalone axioms, punch lines, quote-worthy lines");
    expect(prompt).toContain("Run a best-author negation scan");
    expect(prompt).toContain("Run a whole-article syntax and motif scan before rating.");
    expect(prompt).toContain("Reframing pass for YouTube-inspired essays");
    expect(prompt).toContain("Narrative pass");
    expect(prompt).not.toContain("wait-what contradiction");
    expect(exporter).toContain("missing evals/prepublish-vN.json");
    expect(exporter).toContain("missing evals/title-vN.json");
    expect(exporter).toContain("qualityReviewerVetoCleared");
    expect(exporter).toContain("minimumCategoryTarget");
    expect(exporter).toContain("overall score");
    expect(exporter).toContain("publishPreviewDirAtomically");
    expect(exporter).toContain("assertMaxVoiceAntiFormulaGate");
    expect(exporter).toContain("diagnostic signpost");
    expect(exporter).toContain("paired aphorism");
    expect(exporter).toContain("attributed critic spotlight");
    expect(exporter).toContain("unbulleted label-definition pseudo-list");
    expect(exporter).toContain('name="source-article-sha256"');
    expect(exporter).toContain("articleHash");
    expect(exporter).not.toContain("Draft status:");
    expect(previewVerifier).toContain("Public preview returned HTTP");
    expect(previewVerifier).toContain("Public preview missing");
    expect(previewVerifier).toContain("Public preview contains forbidden");
    expect(previewVerifier).toContain("source article hash mismatch");
    expect(previewVerifier).toContain("Draft status:");
    expect(previewVerifier).toContain("noindex preview");
  });
});
