import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import {
  isBlogPublishAuthorized,
  validateExternalBlogPublishPayload,
} from "@/lib/blog/external-publish-contract";

function validPayload() {
  const links = Array.from(
    { length: 5 },
    (_, index) => `[source ${index + 1}](https://example.com/source-${index + 1})`,
  ).join(" ");
  const article = `# A Reviewed Hermes Article\n\n${links}\n\n${"evidence ".repeat(1550)}`;
  const articleSha256 = createHash("sha256").update(article).digest("hex");
  return {
    runId: "abc123def456",
    packageId: "2026-07-22-weekly-abc123def456",
    article,
    articleSha256,
    review: `article_sha256: "${articleSha256}"\noutcome: pass\n`,
  };
}

function versionTwoPayload() {
  const payload = validPayload();
  const article = payload.article.replace(
    "# A Reviewed Hermes Article",
    "# A Reviewed Hermes Article\n\n![Students learning with a laptop](https://upload.wikimedia.org/wikipedia/commons/8/84/Students-using-laptop.jpg)\n\n*Image: [Students using a laptop](https://commons.wikimedia.org/wiki/File:Students-using-laptop.jpg) by Dvitalo12, licensed under [CC BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/).*",
  );
  const articleSha256 = createHash("sha256").update(article).digest("hex");
  return {
    ...payload,
    contractVersion: 2,
    article,
    articleSha256,
    review: `article_sha256: "${articleSha256}"\noutcome: "pass"\n`,
  };
}

function versionThreePayload() {
  return {
    ...versionTwoPayload(),
    contractVersion: 3 as const,
    publicationDate: "2026-07-27",
  };
}

function canonicalJson(value: unknown): string {
  if (Array.isArray(value)) return "[" + value.map(canonicalJson).join(",") + "]";
  if (value && typeof value === "object") {
    return "{" + Object.keys(value as Record<string, unknown>)
      .sort()
      .map((key) => JSON.stringify(key) + ":" + canonicalJson((value as Record<string, unknown>)[key]))
      .join(",") + "}";
  }
  return JSON.stringify(value);
}

// Read the exact Python-generated bytes from this repository-local fixture.
function pythonProducerV4Fixture() {
  return JSON.parse(
    readFileSync(
      resolve(
        process.cwd(),
        "src/lib/__tests__/fixtures/weekly-blog-publisher-v4.json",
      ),
      "utf8",
    ),
  );
}

function versionFourPayload({
  article,
  readiness = {},
  researchStatus = "research_ready",
}: {
  article?: string;
  readiness?: Record<string, unknown>;
  researchStatus?: string;
} = {}) {
  const finalArticle =
    article ??
    "# Short verified article\n### A `literal` subtitle\n\n![Students using a laptop](https://upload.wikimedia.org/wikipedia/commons/8/84/Students-using-laptop.jpg)\n\n*Image: [Students using a laptop](https://commons.wikimedia.org/wiki/File:Students-using-laptop.jpg) by Dvitalo12, licensed under [CC BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/).*\n\nA short paragraph with [one source](https://example.com/source).\n\n- **Signal:** a useful detail.\n- A second detail.\n\n```ts\nconst link = \"[literal](https://example.com/not-a-link)\";\n\n<script>alert(1)</script>\n```\n";
  const articleSha256 = createHash("sha256").update(finalArticle).digest("hex");
  const sourceUrl = "https://example.org/primary";
  const manifest = {
    status: researchStatus,
    inspected_sources: [
      {
        id: "source-001",
        url: sourceUrl,
        title: "Primary evidence",
        inspected: true,
        locator: "captured_text[0:64]",
        evidence_type: "primary",
        limitations: "Limited setting",
        inspection_proof: {
          tool: "hermes.web.open",
          status: "captured",
          url: sourceUrl,
          content_sha256: "a".repeat(64),
          locator: "captured_text[0:64]",
        },
      },
    ],
    evidence_ledger: [
      {
        claim_id: "claim-001",
        claim: "A measured result.",
        source_ids: ["source-001"],
        locator: "captured_text[0:64]",
        classification: "verified_fact",
        support: "Direct",
        limitations: "Limited setting",
      },
    ],
    research_delta: {
      added: ["A material limitation."],
      corrected: [],
      ruled_out: [],
      materially_improves_decision: true,
    },
  };
  return {
    contractVersion: 4 as const,
    runId: "abc123def456",
    packageId: "2026-07-22-weekly-abc123def456",
    publicationDate: "2026-07-24",
    article: finalArticle,
    articleSha256,
    review: "article_sha256: \"" + articleSha256 + "\"\noutcome: pass\ngates:\n  factual: pass\n  editorial: pass\n  semantic: pass\n",
    framework: {
      id: "research-enriched-article-prompt",
      version: "v6",
      sha256: "00e870819bc1a02aa28e86e49162f7ca93c5f3a05bde072c8b4679c00d5b43af",
    },
    readiness: {
      status: "pass",
      articleSha256,
      factual: { status: "pass", articleSha256, proof: "independent-review" },
      editorial: { status: "pass", articleSha256, proof: "controller-policy" },
      semantic: { status: "pass", articleSha256, proof: "independent-review" },
      format: { status: "pass", articleSha256, proof: "formatter-and-anti-slop" },
      ...readiness,
    },
    researchEvidence: {
      producer: "hermes-weekly-app-articles",
      status: researchStatus,
      manifest,
      manifestSha256: createHash("sha256").update(canonicalJson(manifest)).digest("hex"),
    },
    image: {
      provider: "wikimedia_commons",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/84/Students-using-laptop.jpg",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Students-using-laptop.jpg",
      alt: "Students using a laptop",
      author: "Dvitalo12",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    },
  };
}

describe("external Hermes v4 compatibility", () => {
  it("accepts a fully verified short v4 article", () => {
    const payload = versionFourPayload();
    const result = validateExternalBlogPublishPayload(payload);

    expect(result.visibleWordCount).toBeLessThan(1500);
    expect(result.warnings).toEqual([]);
    expect(result.framework!.sha256).toBe(payload.framework!.sha256);

    const jsonReviewPayload = versionFourPayload();
    jsonReviewPayload.review = JSON.stringify({
      article_sha256: jsonReviewPayload.articleSha256,
      outcome: "pass",
      gates: { factual: "pass", editorial: "pass", semantic: "pass" },
    });
    expect(() => validateExternalBlogPublishPayload(jsonReviewPayload)).not.toThrow();
  });

  it("accepts the same actual Python producer v4 payload fixture", () => {
    const payload = pythonProducerV4Fixture();
    expect(payload.researchEvidence.manifestJson).toMatch(/"confidence":1\.0/);
    expect(payload.researchEvidence.manifestJson).toMatch(/"tiny":1e-07/);
    expect(JSON.parse(payload.review).gates.editorial).toEqual({ status: "pass" });
    expect(() => validateExternalBlogPublishPayload(payload)).not.toThrow();
  });

  it("rejects unknown framework, failed readiness, missing image, tables, and unclosed fences", () => {
    const unknownFramework = versionFourPayload();
    unknownFramework.framework.sha256 = "1".repeat(64);
    expect(() => validateExternalBlogPublishPayload(unknownFramework)).toThrow(/framework/i);

    const missingFramework = versionFourPayload() as Partial<ReturnType<typeof versionFourPayload>>;
    delete missingFramework.framework;
    expect(() => validateExternalBlogPublishPayload(missingFramework)).toThrow(/framework/i);

    const failedOverallReadiness = versionFourPayload({
      readiness: { status: "fail" },
    });
    expect(() => validateExternalBlogPublishPayload(failedOverallReadiness)).toThrow(/readiness/i);

    for (const gate of ["factual", "editorial"] as const) {
      const failedGate = versionFourPayload({
        readiness: { [gate]: { status: "fail" } },
      });
      expect(() => validateExternalBlogPublishPayload(failedGate)).toThrow(new RegExp(gate));
    }

    const failedReadiness = versionFourPayload({ readiness: { format: { status: "fail" } } });
    expect(() => validateExternalBlogPublishPayload(failedReadiness)).toThrow(/readiness|format/i);

    const failedReviewGate = versionFourPayload();
    failedReviewGate.review = failedReviewGate.review.replace("factual: pass", "factual: fail");
    expect(() => validateExternalBlogPublishPayload(failedReviewGate)).toThrow(/factual/i);

    const missingImage = versionFourPayload() as Partial<ReturnType<typeof versionFourPayload>>;
    delete missingImage.image;
    expect(() => validateExternalBlogPublishPayload(missingImage)).toThrow(/image/i);

    const table = versionFourPayload({ article: "# A table\n\n| A | B |\n| --- | --- |\n| 1 | 2 |\n" });
    expect(() => validateExternalBlogPublishPayload(table)).toThrow(/table/i);

    const unclosed = versionFourPayload({ article: "# Unclosed\n\n```ts\nconst value = 1;\n" });
    expect(() => validateExternalBlogPublishPayload(unclosed)).toThrow(/fence/i);
  });

  it("requires research readiness and exact hash binding for every v4 gate", () => {
    const missingResearch = versionFourPayload() as Partial<ReturnType<typeof versionFourPayload>>;
    delete missingResearch.researchEvidence;
    expect(() => validateExternalBlogPublishPayload(missingResearch)).toThrow(/research/i);

    const failedResearch = versionFourPayload({ researchStatus: "research_insufficient" });
    expect(() => validateExternalBlogPublishPayload(failedResearch)).toThrow(/research/i);

    const staleGate = versionFourPayload({
      readiness: {
        semantic: { status: "pass", articleSha256: "0".repeat(64), proof: "review" },
      },
    });
    expect(() => validateExternalBlogPublishPayload(staleGate)).toThrow(/readiness|hash/i);
  });
});

describe("external Hermes blog publishing", () => {
  it("accepts an exact-hash reviewed article with citations", () => {
    const result = validateExternalBlogPublishPayload(validPayload());

    expect(result.title).toBe("A Reviewed Hermes Article");
    expect(result.visibleWordCount).toBeGreaterThanOrEqual(1500);
    expect(result.visibleWordCount).toBeLessThanOrEqual(2000);
    expect(result.inlineUrls).toHaveLength(5);
  });

  it("counts link labels rather than URL path tokens as visible prose", () => {
    const result = validateExternalBlogPublishPayload(validPayload());

    expect(result.visibleWordCount).toBe(1564);
  });

  it("treats more than 2000 words as a warning", () => {
    const payload = versionTwoPayload();
    const article = `${payload.article}\n\n${"additional evidence ".repeat(260)}`;
    const articleSha256 = createHash("sha256").update(article).digest("hex");
    const result = validateExternalBlogPublishPayload({
      ...payload,
      article,
      articleSha256,
      review: `article_sha256: "${articleSha256}"\noutcome: pass\n`,
    });
    expect(result.visibleWordCount).toBeGreaterThan(2000);
    expect(result.warnings).toEqual(["article_over_2000_words"]);
  });

  it("requires a licensed Commons image for version two payloads", () => {
    expect(() =>
      validateExternalBlogPublishPayload({ ...validPayload(), contractVersion: 2 }),
    ).toThrow(/licensed Wikimedia Commons image/i);
  });

  it("accepts a version two article with licensed image attribution", () => {
    expect(validateExternalBlogPublishPayload(versionTwoPayload()).warnings).toEqual([]);
  });

  it("accepts a version three article with a publication date", () => {
    expect(validateExternalBlogPublishPayload(versionThreePayload()).warnings).toEqual([]);
  });

  it("requires a publication date for version three payloads", () => {
    expect(() =>
      validateExternalBlogPublishPayload({
        ...versionThreePayload(),
        publicationDate: undefined,
      }),
    ).toThrow(
      /valid publication date/i,
    );
  });

  it("rejects an article whose supplied hash does not match", () => {
    expect(() =>
      validateExternalBlogPublishPayload({
        ...validPayload(),
        articleSha256: "0".repeat(64),
      }),
    ).toThrow(/SHA-256/i);
  });

  it("rejects a review that is not a pass", () => {
    const payload = validPayload();
    expect(() =>
      validateExternalBlogPublishPayload({
        ...payload,
        review: `article_sha256: "${payload.articleSha256}"\noutcome: revise\n`,
      }),
    ).toThrow(/review outcome/i);
  });

  it("rejects articles without five unique inline source links", () => {
    const payload = validPayload();
    const article = payload.article.replace(/\[source [3-5]\]\([^)]+\)/g, "source");
    const articleSha256 = createHash("sha256").update(article).digest("hex");
    expect(() =>
      validateExternalBlogPublishPayload({
        ...payload,
        article,
        articleSha256,
        review: `article_sha256: "${articleSha256}"\noutcome: pass\n`,
      }),
    ).toThrow(/inline source links/i);
  });

  it("requires an exact bearer token", () => {
    expect(isBlogPublishAuthorized("Bearer secret", "secret")).toBe(true);
    expect(isBlogPublishAuthorized("Bearer wrong", "secret")).toBe(false);
    expect(isBlogPublishAuthorized(null, "secret")).toBe(false);
    expect(isBlogPublishAuthorized("Bearer secret", "")).toBe(false);
  });
});
